### ISSUE TITLE
More granular access to JSON files - Advanced Editor

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/storylines-editor#190]
One conflict our users are running into using the Editor in a remote environment, is that they no longer have access to the file system for making direct changes to the JSON configuration files. This feature could potentially bridge the gap for users who use Visual Studio Code + file system access to edit their products.  

Areas of consideration:
- Allowing the user to edit the entire JSON file for the Storylines product (`_en`, and `_fr`)
- Allowing the user to edit a Highcharts configuration directly
- Allowing the user to edit a RAMP configuration file directly
- Can we integrate some sort of JSON lint integrity check to verify they didn't break the structure?

**Comment by dan-bowerman** [comment]
Related #247

**Comment by dan-bowerman** [comment]
Let me throw an idea in, as this functionality could open a lot of options for us in the medium-term.
![image](https://github.com/ramp4-pcar4/storylines-editor/assets/5294596/8616082a-86fe-4805-bebc-0afe0020e387)

- Allow an "Advanced" view via a tab at the top of the Slide editor
- Selecting this tab gives access to the JSON under the slide, in this case there are two panels that can be directly edited.
- We should verify JSON syntax before the user is allowed to move away from the Advanced tab
- This solves the "customStyles" #247 issue. 
- Other considerations? 

Thoughts?

**Comment by RyanCoulsonCA** [comment]
This makes sense to me! There are various libraries out there that we can use to validate the JSON (here's one example https://www.npmjs.com/package/jsonschema). 

Instead of using our existing text editor where you'd have to insert a bunch of spaces to make it look nice, we can also look at using a JSON editor component. [This one](https://bestkolobok.github.io/vue3-jsoneditor/) seems pretty good (and it seems like it checks for errors as you type).
