### ISSUE TITLE
Keeping the preview feature up to date

### ISSUE THREAD

**Issue by spencerwahl** [ramp4-pcar4/storylines-editor#192]
Currently we have the main storylines panels, etc. sitting in this repo as well. This has been fine since the main repo has not been getting changed much. This will become an issue quite quickly where we will either need to make every PR to both repos or things will become out of sync and the preview will not properly reflect the final product.

We should probably remove everything we can of base storylines components etc. from this repo and rely on the main repo for displaying storylines... this probably means we have to change how the preview button works or how we deploy the editor.

**Comment by mohsin-r** [comment]
One idea is to deploy the main storylines repo somewhere (I think the demo builds already exist or will exist soon?) and then have the preview link to that build instead of the route in the storylines editor repo.

One caveat with this idea that would need testing is if setting the `config` and `configFileStructure` on the window will still work if the new tab has a completely separate URL.

Another (lazy) idea could be to just consolidate the editor and storylines into one repo. 🤷

**Comment by dan-bowerman** [comment]
Related #347
