### ISSUE TITLE
Normalization of Slides

### ISSUE THREAD

**Issue by dan-bowerman** [ramp4-pcar4/storylines-editor#66]
We discussed this in the last meeting, but I didn't take great notes -- what exactly is involved with this?

**Comment by RyanCoulsonCA** [comment]
Basically, the issue was that the editor component for each panel type (chart, map, and image) was using a different method to save and retrieve data. This has been fixed in [this PR](https://github.com/ramp4-pcar4/storylines-editor/pull/64), but just involved modifying the chart and image editors to save their data directly to our ZIP structure, and having them load the data back from the ZIP when needing to be displayed.
